"""
cam_generator.py — Credit Appraisal Memo (CAM) Word Document Generator
Produces a professional bank-grade Word document that looks real enough
to use on Monday morning at Vivriti Capital.
"""

import json
from datetime import datetime
from pathlib import Path

from docx import Document
from docx.shared import Pt, RGBColor, Inches, Cm
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT
from docx.oxml.ns import qn
from docx.oxml import OxmlElement

from scorer import FiveCScore


# ── Colour palette (Vivriti-inspired) ────────────────────────────────────────
DARK_BLUE  = RGBColor(0x1A, 0x35, 0x6E)   # #1A356E — header
MID_BLUE   = RGBColor(0x2E, 0x75, 0xB6)   # #2E75B6 — section headings
LIGHT_BLUE = RGBColor(0xD5, 0xE8, 0xF0)   # #D5E8F0 — table header bg
RED        = RGBColor(0xC0, 0x00, 0x00)
ORANGE     = RGBColor(0xE0, 0x70, 0x00)
GREEN      = RGBColor(0x37, 0x86, 0x30)
BLACK      = RGBColor(0x00, 0x00, 0x00)
WHITE      = RGBColor(0xFF, 0xFF, 0xFF)


def _set_cell_bg(cell, hex_color: str):
    """Set table cell background colour."""
    tc   = cell._tc
    tcPr = tc.get_or_add_tcPr()
    shd  = OxmlElement("w:shd")
    shd.set(qn("w:val"),   "clear")
    shd.set(qn("w:color"), "auto")
    shd.set(qn("w:fill"),  hex_color)
    tcPr.append(shd)


def _bold_run(para, text: str, size: int = 11, color: RGBColor = BLACK):
    run = para.add_run(text)
    run.bold = True
    run.font.size = Pt(size)
    run.font.color.rgb = color
    return run


def _risk_color(level: str) -> RGBColor:
    l = level.upper()
    if l == "CRITICAL": return RED
    if l == "HIGH":     return ORANGE
    if l == "MEDIUM":   return RGBColor(0xBF, 0x8F, 0x00)
    return GREEN


def _recommendation_color(rec: str) -> RGBColor:
    r = rec.upper()
    if r in ("REJECT", "HALT"):  return RED
    if r == "CAUTION":           return ORANGE
    return GREEN


class CAMGenerator:
    """Generates a professional Credit Appraisal Memo as a .docx file."""

    def generate(
        self,
        company_name: str,
        loan_amount_cr: float,
        score: FiveCScore,
        financials: dict,
        gst_analysis: dict,
        research_output: dict,
        user_notes: str = "",
        output_path: str = "CAM_Report.docx",
    ) -> str:

        doc = Document()

        # ── Page margins ─────────────────────────────────────────────────────
        for section in doc.sections:
            section.top_margin    = Cm(2.0)
            section.bottom_margin = Cm(2.0)
            section.left_margin   = Cm(2.5)
            section.right_margin  = Cm(2.5)

        # ── 1. Header ─────────────────────────────────────────────────────────
        self._add_header(doc, company_name, loan_amount_cr, score)

        # ── 2. Executive Summary ──────────────────────────────────────────────
        self._add_executive_summary(doc, company_name, loan_amount_cr, score)

        # ── 3. Five Cs Analysis ───────────────────────────────────────────────
        self._add_five_cs(doc, score, research_output)

        # ── 4. Financial Snapshot ─────────────────────────────────────────────
        self._add_financials(doc, financials, loan_amount_cr)

        # ── 5. GST & Bank Reconciliation ──────────────────────────────────────
        self._add_gst_section(doc, gst_analysis)

        # ── 6. External Research Findings ─────────────────────────────────────
        self._add_research_section(doc, research_output)

        # ── 7. Credit Officer Notes ───────────────────────────────────────────
        if user_notes:
            self._add_section_heading(doc, "7. Credit Officer Field Notes")
            p = doc.add_paragraph(user_notes)
            p.style.font.size = Pt(11)

        # ── 8. Recommendation ─────────────────────────────────────────────────
        self._add_recommendation(doc, score, loan_amount_cr)

        # ── 9. Footer disclaimer ─────────────────────────────────────────────
        doc.add_paragraph()
        disc = doc.add_paragraph(
            f"This Credit Appraisal Memo was generated by Intelli-Credit AI Engine "
            f"on {datetime.now().strftime('%d %B %Y %H:%M')}. "
            f"All findings are based on publicly available information and uploaded documents. "
            f"This report is confidential and intended solely for internal credit committee use."
        )
        disc.runs[0].font.size = Pt(8)
        disc.runs[0].font.color.rgb = RGBColor(0x80, 0x80, 0x80)
        disc.alignment = WD_ALIGN_PARAGRAPH.CENTER

        # ── Save ──────────────────────────────────────────────────────────────
        doc.save(output_path)
        return output_path

    # ─────────────────────────────────────────────────────────────────────────
    def _add_header(self, doc, company: str, amount: float, score: FiveCScore):
        # Title bar
        p = doc.add_paragraph()
        p.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run = p.add_run("CREDIT APPRAISAL MEMORANDUM")
        run.bold = True
        run.font.size = Pt(18)
        run.font.color.rgb = DARK_BLUE

        # Sub-header table
        tbl = doc.add_table(rows=2, cols=4)
        tbl.style = "Table Grid"
        tbl.alignment = WD_TABLE_ALIGNMENT.CENTER

        headers = ["Borrower", "Loan Amount", "Date", "Risk Grade"]
        values  = [
            company,
            f"₹{amount:.0f} Crore",
            datetime.now().strftime("%d %b %Y"),
            f"{score.risk_grade} ({score.overall:.0f}/100)"
        ]

        for i, (h, v) in enumerate(zip(headers, values)):
            hcell = tbl.cell(0, i)
            vcell = tbl.cell(1, i)
            _set_cell_bg(hcell, "1A356E")
            hp = hcell.paragraphs[0]
            hr = hp.add_run(h)
            hr.bold = True
            hr.font.color.rgb = WHITE
            hr.font.size = Pt(10)

            vp = vcell.paragraphs[0]
            vr = vp.add_run(v)
            vr.font.size = Pt(11)
            if h == "Risk Grade":
                vr.bold = True
                vr.font.color.rgb = _recommendation_color(score.recommendation)

        doc.add_paragraph()

    def _add_section_heading(self, doc, text: str):
        p = doc.add_paragraph()
        p.paragraph_format.space_before = Pt(14)
        run = p.add_run(text)
        run.bold = True
        run.font.size = Pt(13)
        run.font.color.rgb = MID_BLUE
        # Bottom border
        pPr = p._p.get_or_add_pPr()
        pBdr = OxmlElement("w:pBdr")
        bottom = OxmlElement("w:bottom")
        bottom.set(qn("w:val"),   "single")
        bottom.set(qn("w:sz"),    "6")
        bottom.set(qn("w:space"), "1")
        bottom.set(qn("w:color"), "2E75B6")
        pBdr.append(bottom)
        pPr.append(pBdr)

    def _add_executive_summary(self, doc, company, amount, score):
        self._add_section_heading(doc, "1. Executive Summary")

        rec_color = _recommendation_color(score.recommendation)

        # Big recommendation box
        p = doc.add_paragraph()
        p.alignment = WD_ALIGN_PARAGRAPH.CENTER
        r1 = p.add_run(f"RECOMMENDATION: {score.recommendation}")
        r1.bold = True
        r1.font.size = Pt(16)
        r1.font.color.rgb = rec_color

        summary_rows = [
            ("Overall Risk Score",    f"{score.overall}/100"),
            ("Risk Grade",            score.risk_grade),
            ("Recommended Rate",      score.suggested_rate),
            ("Character Score (C1)",  f"{score.character:.0f}/100"),
            ("Capacity Score (C2)",   f"{score.capacity:.0f}/100"),
            ("Capital Score (C3)",    f"{score.capital:.0f}/100"),
            ("Collateral Score (C4)", f"{score.collateral:.0f}/100"),
            ("Conditions Score (C5)", f"{score.conditions:.0f}/100"),
        ]

        tbl = doc.add_table(rows=len(summary_rows), cols=2)
        tbl.style = "Table Grid"
        for i, (label, value) in enumerate(summary_rows):
            lc = tbl.cell(i, 0)
            vc = tbl.cell(i, 1)
            if i % 2 == 0:
                _set_cell_bg(lc, "EBF3FB")
                _set_cell_bg(vc, "EBF3FB")
            lr = lc.paragraphs[0].add_run(label)
            lr.bold = True
            lr.font.size = Pt(10)
            vr = vc.paragraphs[0].add_run(value)
            vr.font.size = Pt(10)
            if "Score" in label or "Grade" in label:
                score_val = float(value.split("/")[0]) if "/" in value else 0
                if score_val >= 65: vr.font.color.rgb = RED
                elif score_val >= 45: vr.font.color.rgb = ORANGE
                else: vr.font.color.rgb = GREEN

    def _add_five_cs(self, doc, score: FiveCScore, research: dict):
        self._add_section_heading(doc, "2. Five Cs of Credit Analysis")

        cs = [
            ("C1 — Character", score.character, score.character_reasons,
             "Promoter integrity, litigation, regulatory actions, fraud history"),
            ("C2 — Capacity",  score.capacity,  score.capacity_reasons,
             "Ability to repay from cash flows — DSCR, revenue trend, GST reconciliation"),
            ("C3 — Capital",   score.capital,   score.capital_reasons,
             "Net worth, leverage (D/E ratio), MCA compliance"),
            ("C4 — Collateral",score.collateral,score.collateral_reasons,
             "Security coverage, asset quality, personal guarantees"),
            ("C5 — Conditions",score.conditions,score.conditions_reasons,
             "Sector outlook, macro risk, regulatory environment"),
        ]

        for name, score_val, reasons, desc in cs:
            p = doc.add_paragraph()
            r = p.add_run(f"{name}: {score_val:.0f}/100 risk")
            r.bold = True
            r.font.size = Pt(11)
            # Color by risk level
            if score_val >= 65: r.font.color.rgb = RED
            elif score_val >= 40: r.font.color.rgb = ORANGE
            else: r.font.color.rgb = GREEN

            dp = doc.add_paragraph(desc)
            dp.runs[0].font.size = Pt(9)
            dp.runs[0].font.color.rgb = RGBColor(0x60, 0x60, 0x60)
            dp.paragraph_format.left_indent = Inches(0.3)

            for reason in reasons:
                rp = doc.add_paragraph(reason, style="List Bullet")
                rp.runs[0].font.size = Pt(10)
                rp.paragraph_format.left_indent = Inches(0.3)

    def _add_financials(self, doc, fin: dict, loan_cr: float):
        self._add_section_heading(doc, "3. Financial Snapshot")

        rows = [
            ("Revenue (Last FY)",        f"₹{fin.get('revenue_cr', 'N/A')} Cr"),
            ("Revenue Growth",           f"{fin.get('revenue_growth_pct', 'N/A')}%"),
            ("EBITDA Margin",            f"{fin.get('ebitda_margin_pct', 'N/A')}%"),
            ("Net Worth",                f"₹{fin.get('net_worth_cr', 'N/A')} Cr"),
            ("Total Debt",               f"₹{fin.get('total_debt_cr', 'N/A')} Cr"),
            ("Debt-to-Equity Ratio",     f"{fin.get('debt_to_equity', 'N/A')}x"),
            ("DSCR",                     f"{fin.get('dscr', 'N/A')}x"),
            ("Current Ratio",            f"{fin.get('current_ratio', 'N/A')}x"),
            ("Loan Amount Requested",    f"₹{loan_cr:.0f} Cr"),
            ("Collateral Coverage",      f"{fin.get('collateral_coverage', 'N/A')}x"),
        ]

        tbl = doc.add_table(rows=len(rows), cols=2)
        tbl.style = "Table Grid"
        for i, (label, value) in enumerate(rows):
            lc = tbl.cell(i, 0)
            vc = tbl.cell(i, 1)
            if i % 2 == 0:
                _set_cell_bg(lc, "F5F5F5")
                _set_cell_bg(vc, "F5F5F5")
            lc.paragraphs[0].add_run(label).font.size = Pt(10)
            lc.paragraphs[0].runs[0].bold = True
            vc.paragraphs[0].add_run(value).font.size = Pt(10)

    def _add_gst_section(self, doc, gst: dict):
        self._add_section_heading(doc, "4. GST & Bank Reconciliation (Pillar 1 Analysis)")

        if not gst:
            doc.add_paragraph("No GST data uploaded. Manual verification required.")
            return

        risk_level = gst.get("overall_risk_level", "UNKNOWN")
        p = doc.add_paragraph()
        r = p.add_run(f"GST Risk Level: {risk_level}")
        r.bold = True
        r.font.size = Pt(12)
        r.font.color.rgb = _risk_color(risk_level)

        flags = gst.get("flags", [])
        if flags:
            doc.add_paragraph("Flags Detected:", style="Normal").runs[0].bold = True
            for flag in flags:
                fp = doc.add_paragraph(
                    f"{flag.get('check', '')} — {flag.get('severity', '')} — {flag.get('detail', '')}",
                    style="List Bullet"
                )
                fp.runs[0].font.size = Pt(10)
        else:
            doc.add_paragraph("✅ No material GST discrepancies detected.")

    def _add_research_section(self, doc, research: dict):
        self._add_section_heading(doc, "5. External Research Findings (Pillar 2 — Web Research Agent)")

        fields = [
            ("Promoter Background",    research.get("promoter_background", "Not available")),
            ("Promoter Risk Level",    research.get("promoter_risk_level", "UNKNOWN")),
            ("Litigation Summary",     research.get("litigation_summary", "Not available")),
            ("Litigation Risk Level",  research.get("litigation_risk_level", "UNKNOWN")),
            ("NPA / Default History",  research.get("npa_default_history", "Not available")),
            ("Regulatory Findings",    research.get("regulatory_findings", "Not available")),
            ("Sector Outlook",         research.get("sector_outlook", "Not available")),
            ("Key Findings",           research.get("key_findings", "Not available")),
            ("AI Recommendation",      research.get("research_recommendation", "Not available")),
        ]

        for label, value in fields:
            p = doc.add_paragraph()
            lr = p.add_run(f"{label}: ")
            lr.bold = True
            lr.font.size = Pt(10)
            vr = p.add_run(str(value))
            vr.font.size = Pt(10)
            if label.endswith("Level") or label.endswith("Recommendation"):
                vr.font.color.rgb = _risk_color(str(value))

    def _add_recommendation(self, doc, score: FiveCScore, loan_cr: float):
        self._add_section_heading(doc, "8. Final Credit Recommendation")

        rec = score.recommendation
        color = _recommendation_color(rec)

        p = doc.add_paragraph()
        p.alignment = WD_ALIGN_PARAGRAPH.CENTER
        r = p.add_run(f"DECISION: {rec}")
        r.bold = True
        r.font.size = Pt(20)
        r.font.color.rgb = color

        if rec in ("REJECT", "HALT"):
            reasons = []
            if score.character >= 70:
                reasons.append("Promoter integrity concerns (ED/SFIO/NCLT) — RBI norms prohibit lending to wilful defaulters")
            if score.capacity >= 60:
                reasons.append("Insufficient debt service capacity (DSCR below threshold)")
            if score.capital >= 50:
                reasons.append("Over-leveraged balance sheet")
            if reasons:
                doc.add_paragraph("Key reasons for rejection:").runs[0].bold = True
                for reason in reasons:
                    doc.add_paragraph(reason, style="List Bullet")
        else:
            details = [
                f"Sanctioned Amount: ₹{loan_cr:.0f} Crore",
                f"Indicative Rate: {score.suggested_rate}",
                f"Risk Grade: {score.risk_grade}",
                "Tenure: As per term sheet",
                "Conditions Precedent: Standard Vivriti covenants apply",
            ]
            for d in details:
                doc.add_paragraph(d, style="List Bullet")

        # Signature block
        doc.add_paragraph()
        sig_tbl = doc.add_table(rows=2, cols=3)
        for i, role in enumerate(["Credit Analyst", "Credit Manager", "Credit Committee"]):
            sig_tbl.cell(0, i).paragraphs[0].add_run("_" * 25)
            sig_tbl.cell(1, i).paragraphs[0].add_run(role).bold = True


# ── Standalone test ───────────────────────────────────────────────────────────
if __name__ == "__main__":
    from scorer import FiveCsScorer

    scorer = FiveCsScorer()
    score = scorer.score(
        financials={"dscr": 0.8, "revenue_growth_pct": -5, "debt_to_equity": 3.8,
                    "net_worth_cr": 200, "loan_amount_cr": 500, "collateral_coverage": 1.1,
                    "revenue_cr": 1200, "ebitda_margin_pct": 8, "total_debt_cr": 760,
                    "current_ratio": 0.9},
        gst_analysis={"overall_risk_level": "HIGH",
                      "flags": [{"check": "Circular Trading", "severity": "HIGH",
                                  "detail": "Bank credits 42% of GST turnover"}]},
        research_output={"promoter_risk_level": "CRITICAL",
                         "promoter_background": "Neeraj Singal faces ED investigation and NCLT insolvency proceedings",
                         "litigation_risk_level": "HIGH",
                         "litigation_summary": "NCLT insolvency petition filed by consortium of banks",
                         "npa_default_history": "Declared NPA by SBI, PNB consortium. SARFAESI action initiated.",
                         "regulatory_findings": "ED investigation under FEMA. SFIO probe ongoing.",
                         "sector_risk_level": "HIGH",
                         "sector_outlook": "Steel sector faces overcapacity and import duty pressure",
                         "key_findings": "Promoter under ED investigation. Company in NCLT. Multiple NPA accounts.",
                         "research_recommendation": "HALT"},
        user_notes="Site visit completed. Plant operational. Staff present.",
    )

    gen = CAMGenerator()
    path = gen.generate(
        company_name="Bhushan Steel Ltd",
        loan_amount_cr=500,
        score=score,
        financials={"dscr": 0.8, "revenue_growth_pct": -5, "debt_to_equity": 3.8,
                    "net_worth_cr": 200, "loan_amount_cr": 500, "collateral_coverage": 1.1,
                    "revenue_cr": 1200, "ebitda_margin_pct": 8, "total_debt_cr": 760,
                    "current_ratio": 0.9},
        gst_analysis={"overall_risk_level": "HIGH",
                      "flags": [{"check": "Circular Trading", "severity": "HIGH",
                                  "detail": "Bank credits 42% of GST turnover"}]},
        research_output={"promoter_risk_level": "CRITICAL",
                         "promoter_background": "Neeraj Singal faces ED investigation and NCLT insolvency",
                         "litigation_risk_level": "HIGH",
                         "litigation_summary": "NCLT insolvency petition filed",
                         "npa_default_history": "NPA with SBI, PNB. SARFAESI initiated.",
                         "regulatory_findings": "ED investigation. SFIO probe.",
                         "sector_risk_level": "HIGH",
                         "sector_outlook": "Overcapacity and import duty risks",
                         "key_findings": "Promoter under ED probe. NCLT proceedings. Multiple NPAs.",
                         "research_recommendation": "HALT"},
        user_notes="Site visit done. Plant operational.",
        output_path="CAM_Bhushan_Steel.docx"
    )
    print(f"✅ CAM generated: {path}")